name: CI/CD
on:
  push:
    branches:
    - 'main'
jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test
      - run: npm run lint
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start
  deploy:
    name: Build and Deploy to GCR and Cloud Run
    runs-on: ubuntu-latest
    needs: [code-checks, e2e] 
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-west2-docker.pkg.dev
        docker build -t us-west2-docker.pkg.dev/$GOOGLE_PROJECT/demo/fp-web-image:latest .
        docker push us-west2-docker.pkg.dev/$GOOGLE_PROJECT/demo/fp-web-image:latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fp-web-service --image us-west2-docker.pkg.dev/$GOOGLE_PROJECT/demo/fp-web-image:latest --region us-west2 --platform managed --allow-unauthenticated