name: CI/CD
on:
  - push
jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test
      - run: npm run lint
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start
  build-and-deploy:
    name: Build and Deploy to GCR and Cloud Run
    runs-on: ubuntu-latest
    needs: [code-checks, e2e] 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Build Docker Image
      run: |
        docker build -t abcjobs-web .
    
    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: proyecto-final-abc-jobs-g9
        export_default_credentials: true
    
    - name: Push Docker image to Google Container Registry
      run: |
        docker tag abcjobs-web us-west2-docker.pkg.dev/proyecto-final-abc-jobs-g9/rocaleda-fp-web-docker-repo
        docker push us-west2-docker.pkg.dev/proyecto-final-abc-jobs-g9/rocaleda-fp-web-docker-repo